image: node

stages:
  - build
  - lint
  - deploy


build:
  stage: build
  cache:
    paths:
      - node_modules/
  script:
    - yarn
    - yarn build
  artifacts:
    paths:
      - dist

lint-prettier-tsc:
    stage: lint
    cache:
      paths:
        - node_modules/
    script:
      - yarn prettier:fix
      - yarn lint:fix
      - yarn tsc

pages:
  stage: deploy
  dependencies: 
    - build
  script:
    - mkdir -p public
    - cp dist/index.html dist/404.html
    - mv dist/* public
  artifacts:
    paths:
      - public
  only:
    - master